import type { NextPage } from 'next';
import styles from '../styles/Methodologies.module.css';
import SEO from 'components/SEO';
// import Image from 'next/image';
import NextBtn from 'components/Methodologies/NextBtn';
import Footer from 'components/Layouts/Footer';
// import { Engine, Render, Runner, Bodies, Composite} from 'matter-js';
import { shuffledValues } from 'public/functions/methodologies/values';
import { useSetRecoilState, useRecoilState } from 'recoil';
import { LifeValueState } from 'public/states/Methodologies/LifeValueState';
import { ValueBubble } from 'components/Methodologies/ValueBubble';

const ValueCards: NextPage = () => {
  
  return (<>
    <SEO title='Metanoia' description='Generated by Sangsoo Lee.' />

    <div className={styles.container}>
      <main className={styles.main}>
        
        <h3 className={styles.h3}>What's valuable in your life?</h3>
        <h6 className={styles.middleh6}>
          {`Tap once on the values you like, or twice on the ones you love. Press and hold the ones you don’t like.`}
        </h6>
        <div className={styles.canvas}>
          {shuffledValues().slice(0, 9).map((value, index) => <>
            <ValueBubble key={index} value={value} styles={styles} />
          </>)}
        </div>

        <NextBtn to="/wheel-of-life" />
      </main>
      <Footer />
    </div>
    </>
  )
}

export default ValueCards
