import type { NextPage } from 'next';
import styles from '../styles/Methodologies.module.css';
import SEO from 'components/SEO';
// import Image from 'next/image';
import NextBtn from 'components/Methodologies/NextBtn';
import Footer from 'components/Layouts/Footer';
import React, { RefObject, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { useRecoilValue } from 'recoil';
import { LifeValueState } from 'public/states/Methodologies/LifeValueState';

const WheelOfLife: NextPage = () => {
    const values = useRecoilValue(LifeValueState);  
    const [valueIndex, setValueIndex] = useState(0);
    const [gauge, setGauge] = useState(0);
    // console.log(values);

    const valueContainerRef = useRef<HTMLUListElement>(null);

    useLayoutEffect(() => {
        const scrolledX = valueContainerRef.current?.scrollLeft;
        // scrolledX
        console.log(scrolledX)
        
    }, [valueContainerRef])
    
    const scrollValue = (event: React.MouseEvent<HTMLButtonElement>) => {
        if (event.currentTarget.name === "left" && valueIndex !== 0) {
            setValueIndex(valueIndex - 1);
            // valueContainerRef.current?.scrollTo(400, 0)
        } else {
            setValueIndex
        }
    }

  
    return (<>
        <SEO title='Methodologies | Metanoia' description='Generated by Sangsoo Lee.' />
        <div className={styles.container}>
            <main className={styles.main}>
                <h1 className={styles.h1}>Wheel of Life</h1>
                <h6 className={styles.lefth6}>
                Value the part of the value as much as you think that you already achieved.
                </h6>
                <ul ref={valueContainerRef} className={styles.valuecontainer}>
                    {values.map((value, index) => <>
                        <li className={styles.values} key={index}>
                            <h1 onClick={() => console.log(valueContainerRef.current?.scrollLeft)}>{value}</h1>
                        </li>
                    </>)}
                </ul>
                <div>
                    <button name="left-btn" onClick={scrollValue} className={styles.slider}>left</button>
                    <button name="right-btn" onClick={scrollValue} className={styles.slider}>right</button>
                </div>
                <input type="range" value={gauge} onChange={(event) => setGauge(parseInt(event?.currentTarget.value))} min={0} max={10} />
                {/* CSS will might be:
                input[type="range"] {
                -webkit-appearance: none;
                margin-right: 15px;
                width: 200px;
                height: 7px;
                background: rgba(255, 255, 255, 0.6);
                border-radius: 5px;
                background-image: linear-gradient(#ff4500, #ff4500);
                background-size: 70% 100%;
                background-repeat: no-repeat;
                }

                input[type="range"]::-webkit-slider-thumb {
                -webkit-appearance: none;
                height: 20px;
                width: 20px;
                border-radius: 50%;
                background: #ff4500;
                cursor: ew-resize;
                box-shadow: 0 0 2px 0 #555;
                transition: background .3s ease-in-out;
                }

                input[type=range]::-webkit-slider-runnable-track  {
                -webkit-appearance: none;
                box-shadow: none;
                border: none;
                background: transparent;
                }
                */}

                {/* <div ref={boxRef}>
                <canvas ref={canvasRef} className={styles.canvas}></canvas>
                </div> */}

                <NextBtn to="/wheel-of-life" />
            </main>
            <Footer />
        </div>
    </>)
}

export default WheelOfLife
